<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'BaseHook' => 'src/BaseHook.php',
    'HookUtils' => 'src/HookUtils.php',
    'PostDiffHook' => 'src/PostDiffHook.php',
    'PostLandHook' => 'src/PostLandHook.php',
    'TraphicConfiguration' => 'src/TraphicConfiguration.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PostDiffHook' => 'BaseHook',
    'PostLandHook' => 'BaseHook',
    'TraphicConfiguration' => 'ArcanistConfiguration',
  ),
));
